services:

    #
    # Event Listeners
    #
    elcodi.security.firewall.abstract_listener:
        class: Elcodi\Store\CoreBundle\EventListener\FirewallListener
        abstract: true
        arguments:
            - @event_dispatcher
            - []

    store.core.event_listener.store_disabled:
        class: %store.core.event_listener.store_disabled.class%
        arguments:
            - @=elcodi_config("store.enabled")
            - store.error.store_is_disabled
        tags:
            - { name: firewall_listener, firewall: %bamboo_store_firewall% }

    store.core.event_listener.store_under_construction:
        class: %store.core.event_listener.store_under_construction.class%
        arguments:
            - @=!elcodi_config("store.under_construction")
            - store.error.store_is_under_construction
        tags:
            - { name: firewall_listener, firewall: %bamboo_store_firewall% }
